spring:
  security:
    oauth2:
      client:
        registration:
          salesforce:
            client-id: 3MVG9wt4IL4O5wvIEcrCt_Jm3I62OyvspPT_PhyNqQQJHer90A5f4yB8qdkv502Ztvaa5gThRjG9UwY3ZsH0t
            client-secret: 85D243D6D8B0BE4881BD8D32096350B83AD238AEF8883EBE99BD6745CC9963E4
            scope: api refresh_token offline_access
            authorization-grant-type: authorization_code
            redirect-uri: https://login.salesforce.com/
            api-version: 57.0
            instance-url: https://lrs-dev-ed.develop.my.salesforce.com
            client-name: Salesforce
            client-authentication-method: client_secret_basic
            jwk-set-uri: ''
            user-info-uri: ''
            user-name-attribute: ''
        provider:
          salesforce:
            authorization-uri: https://login.salesforce.com/services/oauth2/authorize
            token-uri: https://login.salesforce.com/services/oauth2/token
            user-info-uri: https://login.salesforce.com/services/oauth2/userinfo
            user-name-attribute: name
            username: anigho7867@gmail.com.dev


logging:
  level:
    org:
      springframework: DEBUG


server:
  port: 8080



